server:
  port: 8080

spring:
  application:
    name: WeeRo-Application
  web:
    resources:
      add-mappings: false
  profiles:
    active: jdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: ${JWT_ACCESS_EXP}
    refreshExp: ${JWT_REFRESH_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}

  admin:
    teacher:
      id: ${TEACHER_ID}
      password: ${TEACHER_PASSWORD}
      name: ${TEACHER_NAME}
      notification-start-time: ${TEACHER_NOTIFICATION_START}
      notification-end-time: ${TEACHER_NOTIFICATION_END}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

firebase:
  credentials:
    json: ${FIREBASE_CREDENTIALS_JSON}

logging:
  level:
    root: INFO
    org.springframework.jdbc: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: OFF